name: Deploy to Environments

on:
  push:
    branches:
      - Dev       # Trigger for Dev environment
      - Qa       # Trigger for QA environment
      - main      # Trigger for Prod environment

jobs:
  dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for Dev
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yourusername/front:dev

      - name: Deploy to Dev
        run: echo "Deployment to Dev environment complete."

  Qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for QA
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: laytharfaoui/front:qa

      - name: Deploy to QA
        run: echo "Deployment to QA environment complete."

  prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: Qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for Prod
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yourusername/front:prod

      - name: Deploy to Prod
        run: echo "Deployment to Prod environment complete."
