name: Deploy to Environments

on:
  push:
    branches:
      - Dev
      - Prd
      - main

jobs:
  deploy:
    name: Deploy to ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: laytharfaoui/front:${{ github.ref_name }}

      - name: Deploy
        run: |
          if [ "${{ github.ref_name }}" == "Dev" ]; then
            echo "Deployment to Dev environment complete."
          elif [ "${{ github.ref_name }}" == "Prd" ]; then
            echo "Deployment to QA environment complete."
          elif [ "${{ github.ref_name }}" == "main" ]; then
            echo "Deployment to Prod environment complete."
          fi
